# Generated by Django 5.0.7 on 2024-12-18 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projet',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='id_projet',
            new_name='id_project',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='id_projet',
            new_name='id_project',
        ),
    ]
