# Generated by Django 5.0.7 on 2024-12-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahp', '0003_alter_comparaison_value_alter_priority_column_sum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparaison',
            name='value',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='priority',
            name='column_sum',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='priority',
            name='local_weight',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='priority',
            name='nrmal_row_sum',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='rank',
            name='global_note',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
